name: Jennifer Chapman (Andreoli-Fang), PhD
title: Technology Leader & AI Specialist
description: Technology leader specializing in AI, machine learning, and cloud solutions. Dr. Jennifer Chapman (formerly Andreoli-Fang) is a CTO and AI expert with over 20 years of experience in telecommunications and cloud computing.
email: hi@nextjen.ai
linkedin: https://linkedin.com/in/nextjen

social:
  - name: LinkedIn
    url: https://linkedin.com/in/nextjen
    icon: fab fa-linkedin
  - name: Email
    url: mailto:hi@nextjen.ai
    icon: fas fa-envelope
  - name: Instagram
    url: https://instagram.com/realnextjen
    icon: fab fa-instagram

navigation:
  - title: Bio
    url: /bio/
  - title: CV
    url: /cv/
  - title: Projects
    url: /projects/
  - title: Publications
    url: /publications/
  - title: AI Resources
    url: /ai-resources/ 
  - title: Paintings
    url: /paintings/ 