name: Jennifer Andreoli-Fang, PhD
title: Technology Leader & AI Enthusiast
description: Technology leader specializing in AI, machine learning, and cloud solutions
email: web@nextjen.ai
linkedin: https://linkedin.com/in/nextjen

social:
  - name: LinkedIn
    url: https://linkedin.com/in/nextjen
    icon: fab fa-linkedin
  - name: Email
    url: mailto:hi@nextjen.ai
    icon: fas fa-envelope
  - name: Instagram
    url: https://instagram.com/realnextjen
    icon: fab fa-instagram

navigation:
  - title: Bio
    url: /bio/
  - title: CV
    url: /cv/
  - title: Projects
    url: /projects/
  - title: Publications
    url: /publications/
  - title: AI Resources
    url: /ai-resources/ 
  - title: Paintings
    url: /paintings/ 